name:       'DUB'

brandimage: 'images/nav_logo.png'
brandtext:  'DUB'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'About DUB'
      link: 'aboutdub.html'
    - text: 'DUB Seminar'
      link: 'seminar.html'
#    - text: 'People'
#      link: 'people.html'
#    - text: 'Resources'
#      link: 'resources.html'
    - text: 'Getting Involved'
      link: 'gettinginvolved.html'

collections:
  people:
    output: false
  seminars:
    output: true

defaults:
  - scope:
      type: seminars
    values:
      layout: seminar

future: true

exclude:
  # base
  - base/__init__.py
  - base/docker
  - base/invoke
  - base/readme
  - base_sample
  # Bootstrap source files
  - bootstrap/less
  # CSS/LESS files that are included by other less files and cannot compile on their own
  - css/styles.less
  - css/base/base_styles.less
  - css/base/base_variables.less
  - css/base/syntax.css
  - css/base/bar/base_bar.less
  - css/base/freelancer/base_freelancer.less
  - css/base/freelancer/freelancer.less
  - css/base/freelancer/mixins.less
  - css/base/freelancer/variables.less
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env36
  - env38
  - env39
  - requirements3.in
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  - readme
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Secrets
  - secrets
  # Tests
  - tests
